### ISSUE TITLE
Questions on  gpu programming v cpu

### ISSUE THREAD

**Issue by zakelwe** [rogerdahl/cuda-collatz#1]
Hello Roger,

I found this project very interesting.   After not doing C programming for over 20 years my old friend asked me to join him in doing a Collatz program as a hobby to while away the hours.

We are actually doing the max N value for any given N, rather than the delay. On my 4 core cpu I am up to 60, with no sieving, but using general number optimisations plus threaded so using 3 of the 4 cores ( it is my main PC so it needs to do something else as well on the fourth core, like write this  :) ).

Being very rusty at programming, but having seen your excellent effort, I wondered whether you could advise on moving my code ( I use generic Visual Studio v17    C code ) to the graphics card; note I am an an absolute beginner at graphics card programming.  The advantages are clear of course, graphics cards being massively multi-parallel. I have a 970 GTX in the machine not doing much nowadays apart from the odd game.... getting old :)

I am not sure if you are reading this page anymore, but I thought I would reach out on the off chance.

All the best, and well done on your work with this. I am always in awe of people who are on a higher rung of the programming ladder. Same for the maths bods !!!!

**Comment by rogerdahl** [comment]
Hey, thanks for the kind words :)

GPU programming is fun and rewarding. Go for it!

I don't have time to help in a general capacity in your GPU adventures, but if you have specific questions, I'll try to answer them, or at least point you in the right direction for where to find answers.

I have GitHub set to email me whenever someone opens an issue on a project of mine, but if you send an email to my git@dahlsys.com email address, I'll reply from my regular address so that you can use that in the future if you like.
